### ISSUE TITLE
Want to join the introDH-Hub?

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#1]
Please respond here with your new GitHub account to ask to be added as a collaborator on this repo!

**Comment by natalyamyers** [comment]
This is Natalya Myers, my username is @natalyamyers I would like to be added!

**Comment by am0eba-byte** [comment]
Add me please! This is Mia

**Comment by amw6765** [comment]
My name is Anthony W @amw6765. @ebeshero please add me as a collaborator!

**Comment by bpm5520** [comment]
This is Brandon M, I would like to be added as a collaborator!

**Comment by tomsheehy** [comment]
Hi, Dr. B! I would like to be added please.

**Comment by arrowarchive** [comment]
This is Rachel G, and I'd like to be added, please!

**Comment by JesseBeckwith1998** [comment]
This is Jesse B and would like to be added, please.

**Comment by ebeshero** [comment]
@natalyamyers @am0eba-byte @amw6765 @arrowarchive @JesseBeckwith1998 @tomsheehy @bpm5520 I've just invited each of you to join this repo! You'll need to accept my invitation to join: Do that my checking the email you used to create your GitHub account, and accepting the invite.

**Comment by dxh405** [comment]
Hello Dr.B! I would like to be added!

**Comment by AlexanderRAnderson** [comment]
This is Alex Anderson. I would like to be added.

**Comment by mws6176** [comment]
This is Matt Schnelle, I would like to be added.

**Comment by BenS6206** [comment]
This is Ben Simon, I would like to be added please!

**Comment by Joelpie** [comment]
Hello, my username is @Joelpie, I'd like to be added.

**Comment by kzp308** [comment]
This is Kyara Parrish, I would like to be added please!

**Comment by gabbiedoster** [comment]
Hello, this is Gabbie Doster, I would like to be added.

**Comment by Janman813** [comment]
Hi this is Janet Pituch, I would like to be added.

**Comment by jzm6677** [comment]
This is Jalen Moss, I would like to join.

**Comment by NickyV1234** [comment]
hey its Nicky i would like to be added

**Comment by xsierraallen** [comment]
Hey! It's Sierra and I would love to be added.

**Comment by nxh5137** [comment]
It's Nathan... can I join?

**Comment by ypl5391** [comment]
This is Yuchen Liu, may I join in?

**Comment by pxl5083** [comment]
This is Peter Lamis, If I am not already, may I be added?

**Comment by ebeshero** [comment]
@argynarg @Joelpie @pxl5083 @ypl5391 Please check the email you used to create your GitHub account, and accept the invitation from me to join this repo.

**Comment by hjl5363** [comment]
This is Harrison Lilley and I would like to please be added. @ebeshero
