### ISSUE TITLE
Share Draft Timemaps

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#19]
If you like, share links to your Google Sheet and published Timemapper here. Let us know if there's something you want to debug here.

**Comment by arrowarchive** [comment]
I'm gonna test some things with images. Most of them are working fine, but two images in particular haven't been showing up. 

I'll be adding these images over the weekend, so the image files can be checked. The areas I might need debugging on are F7 and F8, so if the images don't show on the official website, let me know.

Google sheet: https://docs.google.com/spreadsheets/d/1_Xn7QPDnXbW7TTinEkH0JvU7liOlLJ-uhc0OpvWmQyc/edit?usp=sharing 

Time Map: http://timemapper.okfnlabs.org/anon/tyjzzm-time-map-starter-rachel-gerzevske

**Comment by am0eba-byte** [comment]
[My Google sheet](https://docs.google.com/spreadsheets/d/1jpp-EhNMMI562E084DBBibnZrEgaFUCWgZxHY2VJ9K0/edit#gid=0)
[ZeTimeMapper](http://timemapper.okfnlabs.org/anon/801vn2-timemapstarter-digit100#0)
