### ISSUE TITLE
Messing with Markdown

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#2]
This is an issue to help introduce you to [Markdown](https://guides.github.com/features/mastering-markdown/). Reply to this and experiment with markdown!

# Heading 1
### heading 3

- list item

- list item
   - list in list
   - list in list 

Sharing code in code blocks:
`<tags>`  are going to disappear
Code block:

```xml
<xml>
     <tag type="markup">Markup is awesome!</tag>
</xml>

```

**Comment by am0eba-byte** [comment]
### nice marmot

```
<quote who="Walter"> 
That rug really tied the room together, did it not?
</quote>
```
# Well, that's just, like,
## your *opinion*
man

**Comment by amw6765** [comment]
# Heading Bold 
<hide> tag 
## Lincoln

**Comment by arrowarchive** [comment]
##Heading Bold

**Comment by Joelpie** [comment]
# Markdown 2:
## Electric Boogaloo

**Comment by dxh405** [comment]
**BOLD**
*Italics*

As Danny once said:
> I did this once already but that's ok
> Its good practice

**Comment by arrowarchive** [comment]
1. Realize that I have no experience with code
1. Practice code on a Markdown page
1. repeat

**Comment by tomsheehy** [comment]
*Italics*
_Italics_
~~Strike~~

**Comment by natalyamyers** [comment]
# playing with markdown
I have done this before **but** I could always use more practice

**Comment by gabbiedoster** [comment]
Practicing markdown

**Comment by arrowarchive** [comment]
**and it's ONE!**
**TWO!!**
**Three strikes, you're out! at the old, ball game!!!**

**Comment by AlexanderRAnderson** [comment]
# **Bold** and *Brash*
## **More like, belongs in the trash**

**Comment by pxl5083** [comment]
It has been so long since I have coded

**Comment by bpm5520** [comment]
*Italics*
**Bold**
_**Bold and Italic**_
~~Nothing to see here~~

**Comment by kzp308** [comment]
# Let's see if this works cause i haven't coded in a long time

## Let's see if this works cause i haven't coded in a long time

**Comment by tomsheehy** [comment]
😎

**Comment by kzp308** [comment]
<h2> ok yes it did lol </h2>

**Comment by gabbiedoster** [comment]
I've never coded not sure how this works

**Comment by arrowarchive** [comment]
~~this is the best I can do for now~~

**Comment by kzp308** [comment]
<ol>
im 
just
practicing
</ol>

**Comment by arrowarchive** [comment]
@ebeshero My constant notifications were due to you inviting people.

**Comment by ebeshero** [comment]
@arrowarchive This is probably going to send you a notification!

**Comment by NickyV1234** [comment]
### heading 1?
### heading 2?
### hello

- stuff

- thingss

**Comment by kzp308** [comment]
<ol>
<h1> my list </h1>
<h2>
<li> i have some css experience</li>
<li> but this is much easier for me</li>
<li> we'll see if i get the hang of markdown</li>
</h2>
</ol>

**Comment by ebeshero** [comment]
Markdown codeblock:
```
# header 1
###### header 6
```

**Comment by arrowarchive** [comment]
😛

**Comment by arrowarchive** [comment]
😉 🤔 🤷‍♀️

**Comment by am0eba-byte** [comment]
### Public Service Announcement
## top secret
if you hover over someone's username w/ your cursor, you can see their lil profile bio

**Comment by BenS6206** [comment]
this is **bold**
this is _not bold_


1. This
1. is
1. a
1. list!

[Link](google.com)

**Comment by xsierraallen** [comment]
I think this is **bold**
This is _italics_

**Comment by xsierraallen** [comment]
**A List**
1. Did
1. I
1. Do
1. It?

**Comment by Meganpeck115** [comment]
> # Let's see if this works cause i haven't coded in a long time
> ## Let's see if this works cause i haven't coded in a long time

Yeah, I am not quite sure on how all of this works. I am confused!

**Comment by JesseBeckwith1998** [comment]
**This is is going to be bold**
_This text will be italicized_

Hopefully

**Comment by nxh5137** [comment]
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

### 100 100 times 👍

**Comment by pxl5083** [comment]
1. Is this right?

**Comment by pxl5083** [comment]
<xml>
     <tag type="markup">Markup is awesome!</tag>
</xml>

**Comment by mws6176** [comment]
# Shot in the dark
1. I think this is **bold** 
2.  *This should be italicized*
3.  _Hopefully **this** is **both**_

**Comment by Tonya-Velcko** [comment]
# Is this how you header?
## This is me trying my best
1. *Realizing I have no experience with actually typing code*
2. **Panic**
3. ~~Literally my only experience with coding is via elementary programs like Scratch~~
