### ISSUE TITLE
Hypothes.is account issues

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#24]
Any issues with Hypothes.is access? Post here so we can help each other. Ping Dr. B at @ebeshero in your post so I see it right away.

**Comment by arrowarchive** [comment]
@ebeshero, were we supposed to do the annotations before class today? I was planning on doing them this weekend. If I have any issues with Hypothes.is, I'll post them here!

**Comment by ebeshero** [comment]
@arrowarchive No: I'm just setting this up prior to class. This is to help with our next assignment.
