### ISSUE TITLE
Aurore

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#25]
Leave some notes about this game here if you like!

**Comment by arrowarchive** [comment]
It was mentioned in the call, but I've been having framerate issues in the game. It should run fine, as I've run more detailed games such as _Ori and the Will of The Wisps_ with little to no lag. Here, it's a problem for me. My computer has 8 GB of RAM, so it should run most games pretty well. 

I have a theory about it: almost everything in the game can be interacted with. The pathways are interactable, the random stones floating around are interactable, even areas that have disassembled and are floating in the air can be interacted with. It's as if the computer is struggling to process it all.
