### ISSUE TITLE
Games for Mac Users

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#28]
@amw6765 Please post your game finds here that are friendly for Mac users.

**Comment by amw6765** [comment]
[Earths Secrets](https://anicetngrt.itch.io/earths-secrets)

[Swarm of the Plague Babies](https://stairfallinstitute.itch.io/swarm-of-the-plague-babies)

[Sabatoge in Stormy Skies](https://ghostpattern.itch.io/sabotage-in-stormy-skies
)

[ESC](https://radicaldreamland.itch.io/esc?download
)

**Comment by AnicetNgrt** [comment]
Thanks for featuring my game !
