### ISSUE TITLE
Join the introDH-Hub as a collaborator

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#30]
Please respond here with your new GitHub account to ask to be added as a collaborator on this repo! (Also, please identify yourself by name, together with your new GitHub handle.)

**Comment by amayadwillis** [comment]
Please add me to this repo @amayadwillis :)

**Comment by ebeshero** [comment]
Hi! I'm Dr. B (Elisa Beshero-Bondar), and my GitHub is @ebeshero

**Comment by nmiano** [comment]
@ebeshero, This is my account > @nmiano

**Comment by kjc6167** [comment]
Please add me as a collaborator: @kjc6167 (My name is Kyle Cronin by the way)

**Comment by Awebster7** [comment]
Hello! This is Aliya Webster, please add me to this repo @Awebster7

**Comment by chrisklein10** [comment]
Hello, i'm Chris Klein, please add me as a collaborator on this repo, my handle is @chrisklein10

**Comment by jbg5721** [comment]
Hi, I am Joey Gardiner please add me to this repo! @jbg5721

**Comment by ras6164** [comment]
My username is @ras6164 (Ryan Scott), @ebeshero please add me as a collaborator to this repo.

**Comment by ebeshero** [comment]
If you've posted a request to join the introDH-Hub, I've now responded to each of you with an invitation. If I responded with a little emoji, that means you'll definitely have an invitation from me, and you'll find it in the email you used to set up your GitHub account. Go and accept my invitation and you'll be ready to post to this repo!

**Comment by ebeshero** [comment]
If I've sent you an invitation to the newtFire organization, you can also accept it just by visiting https://github.com/newtfire

**Comment by Jakeruff29** [comment]
Please add me as a collaborator @jakeruff29 (Jake Ruffalo)

**Comment by erinmooney** [comment]
Please add me as a collaborator @erinmooney

**Comment by SoulEpicness** [comment]
Please add me as a collaborator @SoulEpicness (David Allen II)

**Comment by aidanvray** [comment]
My username is @aidanvray, could you please add me as a collaborator?

**Comment by debbie-evans** [comment]
My user name is @debbie-evans can you please add me as a collaborator? thanks!

**Comment by thammer12499** [comment]
My username is @thammer12499 this is Thomas Hammer, could you please add me as a collaborator? Thank you!

**Comment by WillStill** [comment]
Please add me as a collaborator @WillStill

**Comment by Tonya-Velcko** [comment]
Please add me as a collaborator @Tonya-Velcko

**Comment by luh429** [comment]
Please add me as a collaborator @luh429 I am Logan Hering

**Comment by TOMZS1** [comment]
Can you add me as a collaborator please @TOMZS1. Thank you @ebeshero

**Comment by gvt5036** [comment]
Please add me as a collaborator! My username is @A-Little-Coconut , this is Graesyn Tefft

**Comment by adam-vanscoyoc** [comment]
Please add me @adam-vanscoyoc
