### ISSUE TITLE
Adding Club Collaborators 

### ISSUE THREAD

**Issue by bmg5877** [newtfire/introDH-Hub#34]
My username is @bmg5877. @ebeshero, please add me as a collaborator to this introDH-Hub.

**Comment by ztd5049** [comment]
I am @ztd5049, Digit 100 student. @ebeshero, please add me as a collaborator to the introDH-Hub repo.

**Comment by ebeshero** [comment]
@bmg5877 You appear already to have access to the introDH-Hub. I have also sent you an invitation to the newtfire GitHub organization (should be in your email).

@ztd5049 I have just invited you to the introDH-Hub. You'll need to accept my invitation (in your email) to join the repo.

**Comment by ZakMurphy191** [comment]
My username is @ZakMurphy191. @ebeshero, please add me as a collaborator to this introDH-Hub.
