### ISSUE TITLE
Requests to be added as a Collaborator on This Repo

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#36]
Please post here to introduce your GitHub self to our Fall 2021 DIGIT 100 class, and request to be added as a collaborator on this repo!

(If you've already posted in another issue, that's okay, too. I'll see it, and you don't need to do anything more. This new issue should collect most of the class's requests.)

**Comment by IsabelCriswell** [comment]
Hi  @ebeshero ! My username is @IsabelCriswell please add me as a collaborator!

**Comment by Yuying-Jin** [comment]
Hi, @ebeshero. Please add me as a collaborator to this Hub. My username is @Yuying-Jin.

**Comment by AlexanderVaughan** [comment]
Hi, @ebeshero Please add me as a collaborator to this Hub. My username is @AlexanderVaughan

**Comment by AloraBenitez** [comment]
Hi, @ebeshero Please add me as a collaborator to this hub. My username is @AloraBenitez

**Comment by julianjmg** [comment]
hi @ebeshero Please add me as a collaborator to this hub. My username is @julianjmg

**Comment by cjp6019** [comment]
hi @ebeshero. I'm Chris Pedersen, username is @cjp6019, and pretty please add me as a collaborator.

**Comment by jks6769** [comment]
Hi @ebeshero. Please add me as a collaborator to this hub. My username is @jks6769

**Comment by als7294** [comment]
Hey @ebeshero . Please add me as a collaborator. My username is @als7294

**Comment by gak5275** [comment]
Hi @ebeshero . Please add me as a collaborator. My username is @gak5275 .

**Comment by ebeshero** [comment]
If you have requested to be added as a collaborator before this point (1:15pm on Thurs. 9/2/'21), you have been **invited** to join. Please check the email you used to create your GitHub account for an invitation to join the introDH-Hub, and accept the invitation--and you'll be in!

**Comment by tph5501** [comment]
Hi **@ebeshero**. Please add me as a collaborator. My username is **@tph5501**.

**Comment by ZakMurphy191** [comment]
Hi, @ebeshero. Please add me as a collaborator to this Hub. My username is @ZakMurphy191.

**Comment by Lec5584** [comment]
Hi @ebeshero , my name is @lec5584. please add me as a collaborator.

**Comment by Msd5534** [comment]
Hi, @ebeshero Please add me as a collaborator. My username is @msd5534

**Comment by tec5271** [comment]
Hi, @ebeshero Please add me as a collaborator. My username is @tec5271

**Comment by fkb5105** [comment]
Hi, @ebeshero. Please add me as a collaborator to this hub. My username is @fkb5105

**Comment by SCD5363** [comment]
Hi, @ebeshero. Please add me as a collaborator to this hub. My username is @SCD5363

**Comment by bkb5699** [comment]
Hi, @ebeshero. Please add me as a collaborator to this hub. My username is @bkb5699

**Comment by jeromenacey** [comment]
Hi, @ebeshero. Please add me as a collaborator to this hub. My username is @jeromenacey
