### ISSUE TITLE
Class Discussion Exercise: Introducing Voyant Tools

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#42]
Choose of these webpages and copy the text from the page:

* [Kew Gardens](http://digital.library.upenn.edu/women/woolf/monday/monday-07.html)
* [Girl](https://www.newyorker.com/magazine/1978/06/26/girl)
* [Tell-Tale Heart](https://poemuseum.org/the-tell-tale-heart/)

Take a few minutes to read the story you chose. 

Go to one of these sites to access Voyant Tools: 
* main site: https://voyant-tools.org/
* mirror site: https://service.sadilar.org/voyant/ 

Copy and paste **just the text of the story** into the Voyant window. Then let's look at the outputs. 

In your own view from reading, what seem to be some of the most important words and ideas?

What do you notice in the results? How do they compare with your reading of the text?

**Comment by Yuying-Jin** [comment]
On my own view from the story Kew Gardens, "the " and "women" seem to be the most important words.

This tool can get the most frequent words and list all phrases. It also can analyze the correlation between two different words and calculate vocabulary density and average words per sentence. It found in the story Kew Gardens,  "bed", "flower", "women" are the most important words, which appear at least 10 times.
