### ISSUE TITLE
Mystery Text Discussion of fc.txt 

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#43]
Post your ideas and findings and screen captures about fc.txt here!

**Comment by bmg5877** [comment]
While exploring the fc text, I came across some interesting phrases and words. First, on Antconc, I found the phrase "of the". One of the lines in the text associated with it was "Out of the court in agony. The tortures of the accused did not equal mine; she was in my hovel". When I searched in Voyant, a couple of the most common words were "Man", "Father", "Time", and "Elizabeth". Maybe this text has something to do with someone fighting for something in a court case? Maybe a mother fighting against a father that has wrongfully treated her and her children?
![antconc fc](https://user-images.githubusercontent.com/89885138/136801370-7d15d1be-3c3b-4680-b4da-9e298c8917e3.png)
![voyant fc ](https://user-images.githubusercontent.com/89885138/136801386-05a43d8c-1b9b-4ce2-a47b-6829db707371.png)

**Comment by ZakMurphy191** [comment]
While exploring the FC.txt I found most of the interest in "I am", "court" ,"I will" ,"my father" and etc... a phrase I found with my father was:
"There was a considerable difference between the ages of my parents, but this circumstance seemed to unite them only closer in bonds of devoted affection."
This shows me that in the reading there is some disconnect between the mother and father which brings me to voyant where it states that the most common words were man, life, time, shall, and Elizabeth. This is a perfect example where it matches up with Antconc. So I think if I were to read the book in its entirety I believe that the book would be about a father and Elizabeth finding struggles, having a disconnection, and arguing throughout, there was also death in a most common phrase. Another part I believe is a close family member died and that brought the disconnection with them? There were a lot of usage of "treating right", so maybe people were not treating each other fairly? These are what I got from the exercise I look forward to seeing what others have to say!

<img width="1680" alt="Screen Shot 2021-10-12 at 1 57 55 PM" src="https://user-images.githubusercontent.com/89998845/137009260-1717ad55-396b-43ba-82c2-c11ba9e1c207.png">
<img width="1680" alt="Screen Shot 2021-10-12 at 2 23 58 PM" src="https://user-images.githubusercontent.com/89998845/137009267-ad9a6633-c315-4f49-a03b-d8c1faa132a1.png">
<img width="294" alt="Screen Shot 2021-10-12 at 2 15 29 PM" src="https://user-images.githubusercontent.com/89998845/137009344-0091d4e1-f7f0-460c-9d66-6d377005f22f.png">
<img width="416" alt="Screen Shot 2021-10-12 at 2 20 14 PM" src="https://user-images.githubusercontent.com/89998845/137009356-868938d6-2f69-4f9c-8afe-52066397c061.png">

**Comment by ZakMurphy191** [comment]
> While exploring the fc text, I came across some interesting phrases and words. First, on Antconc, I found the phrase "of the". One of the lines in the text associated with it was "Out of the court in agony. The tortures of the accused did not equal mine; she was in my hovel". When I searched in Voyant, a couple of the most common words were "Man", "Father", "Time", and "Elizabeth". Maybe this text has something to do with someone fighting for something in a court case? Maybe a mother fighting against a father that has wrongfully treated her and her children?
> ![antconc fc](https://user-images.githubusercontent.com/89885138/136801370-7d15d1be-3c3b-4680-b4da-9e298c8917e3.png)
> ![voyant fc ](https://user-images.githubusercontent.com/89885138/136801386-05a43d8c-1b9b-4ce2-a47b-6829db707371.png)

I agree with you I believe that it has something to do with the arguing within the family nice work!

**Comment by bmg5877** [comment]
> While exploring the FC.txt I found most of the interest in "I am", "court" ,"I will" ,"my father" and etc... a phrase I found with my father was: "There was a considerable difference between the ages of my parents, but this circumstance seemed to unite them only closer in bonds of devoted affection." This shows me that in the reading there is some disconnect between the mother and father which brings me to voyant where it states that the most common words were man, life, time, shall, and Elizabeth. This is a perfect example where it matches up with Antconc. So I think if I were to read the book in its entirety I believe that the book would be about a father and Elizabeth finding struggles, having a disconnection, and arguing throughout, there was also death in a most common phrase. Another part I believe is a close family member died and that brought the disconnection with them? There were a lot of usage of "treating right", so maybe people were not treating each other fairly? These are what I got from the exercise I look forward to seeing what others have to say!
> 
> <img alt="Screen Shot 2021-10-12 at 1 57 55 PM" width="1680" src="https://user-images.githubusercontent.com/89998845/137009260-1717ad55-396b-43ba-82c2-c11ba9e1c207.png">
> 
> <img alt="Screen Shot 2021-10-12 at 2 23 58 PM" width="1680" src="https://user-images.githubusercontent.com/89998845/137009267-ad9a6633-c315-4f49-a03b-d8c1faa132a1.png">
> 
> <img alt="Screen Shot 2021-10-12 at 2 15 29 PM" width="294" src="https://user-images.githubusercontent.com/89998845/137009344-0091d4e1-f7f0-460c-9d66-6d377005f22f.png">
> 
> <img alt="Screen Shot 2021-10-12 at 2 20 14 PM" width="416" src="https://user-images.githubusercontent.com/89998845/137009356-868938d6-2f69-4f9c-8afe-52066397c061.png">

I agree with your point of there was some disconnect between the mother and father. It does seem very likely after looking at all the key phrases from yours and how they match up with mine. Great job!

**Comment by jeromenacey** [comment]
In the fc.txt, some of the n-grams that showed up the most frequently for my filter were the following: "which I had", "I did not", "I could not", "my father", "that I had". "Which I had" tells me, as the reader, that the author of this text must have lost something, or someone. That, coupled with the fact that it is the most commonly used n-gram tells me that they most likely are telling a story in the past tense. The "my father" n-gram being used as often as it is suggests to me that the author might be talking about their family in the past. Now, without reading the whole text, I can't know for sure, but guessing from the other common n-grams, this story is for sure told in the past tense, the author's father has passed, and the author might be wishing for him to be back? Or may be reminiscing in a positive way about good times that the two shared together.
![antconc mystery text](https://user-images.githubusercontent.com/89986557/137012617-fa722f6d-a35b-4984-b552-87dfdd4f1165.JPG)

**Comment by tec5271** [comment]
When exploring this text document in antconc to find repeating cases of phrases I was met with some pretty surprising results. I upped the minimum number of n-grams to 3 and max to 5 just to get some narrowed results and "which I had" was the top one. During this text that phrase hit 38 times which to me is quite impressive. The common occurrence of this phrase made me realize that this text is a story being told past tense. Its also led me to believe that the writer of this text is trying to put forth his/her experiences. There a other phrases that such as "whom I had" that support my guess that this is a story being told after the fact. In all analyzing the n-grams on antconc for this text file really gave some clear cut views and thoughts onto what this could really be about and how it is being told. [](ur
![Screenshot (4)](https://user-images.githubusercontent.com/89924700/137059001-6d6a5e20-25da-4b57-8f17-44d27a9cd49b.png)
l)
Secondly came voyant, this analyzation while more basic than the antconc program it is still interesting to see the i believe we called it "word cloud". To my surprise there wasnt anything out of the ordinary in this portion of analyzing the text. Words like "man" and "father" that popped up on antconc were the most used words throughout this text file. I would like to find a similar themed text and compare and contrast the two to see if another writer uses the same words as often or if they find more ways to spice up their word selection
![Screenshot (5)](https://user-images.githubusercontent.com/89924700/137059881-3ae307c3-dd1c-40f9-8b9e-dfa1189e2626.png)
.

**Comment by jks6769** [comment]
While exploring the fc.txt file, I made the minimum number of n-grams to 2 and the max to 4, the phrase that come up the most frequently was "of the", it cam up a total of 527 times. The phrase was often used to indicate a person or thing in context to a sentence. From looking at the text while in the voyant word cloud you can get a little understanding of what the text is about.
![Screenshot (2)](https://user-images.githubusercontent.com/89991408/137337300-49d48528-b71a-44b5-8e7b-1f3250c642d5.png)
![Screenshot (3)](https://user-images.githubusercontent.com/89991408/137337305-c080c0c9-542a-4e0f-ba90-237e625b74c1.png)
