### ISSUE TITLE
Requests to be Added as a Collaborator to This Repo

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#48]
Please post here to introduce your GitHub self to our Spring 2022 DIGIT 100 class, and request to be added as a collaborator on this repo!

**Comment by ebeshero** [comment]
Sample response to demonstrate direct linking to an issue comment.

**Comment by jms9354** [comment]
requesting to be added as a collaborator

**Comment by sydneymcdonough** [comment]
requesting to be added as a collaborator

**Comment by tfk5306** [comment]
request to be added

**Comment by ghost** [comment]
requesting to be added as a collaborator

**Comment by mmw6204** [comment]
request to be added

**Comment by MyeishaF** [comment]
request to be added

**Comment by abbeyypalmer** [comment]
request to be added

**Comment by tristinhain** [comment]
Requesting to be added as a collaborator

**Comment by ebeshero** [comment]
If I put a "hooray" emoji on your request, that means I have sent you an invitation to join the introDH-Hub as a collaborator! Go and check the email you used to configure GitHub, and look for an invitation from me or the introDH-Hub to join, and **click through to Accept** on the invitation.

**Comment by ipm5130** [comment]
Requesting to be added!

**Comment by jmh7557** [comment]
request to add

**Comment by ebeshero** [comment]
@ipm5130 and @jmh7557 I've now sent you an invitation to join the introDH-Hub as a collaborator! Go and check the email you used to configure GitHub, and look for an invitation from me or the introDH-Hub to join, and **click through to Accept** on the invitation.

**Comment by TheMightyDaltho** [comment]
> Sample response to demonstrate direct linking to an issue comment.

Requesting to be added as a collaborator, Sorry I'm late.

**Comment by JakeSala** [comment]
Requesting to be added as a collaborator

**Comment by ebeshero** [comment]
@TheMightyDaltho @JakeSala I've now sent you an invitation to join the introDH-Hub as a collaborator! Go and check the email you used to configure GitHub, and look for an invitation from me or the introDH-Hub to join, and click through to Accept on the invitation.

**Comment by JiminyKricket0323** [comment]
requesting to be added as a collaborator

**Comment by hannahiadeluca** [comment]
requesting to be added as a collaborator

**Comment by Brycekrispies33** [comment]
add me plz :)

**Comment by ebeshero** [comment]
@Brycekrispies33 I nearly missed yours because it arrived so late and you didn't post anything in Canvas. :-(

**Comment by JaxAbele** [comment]
Please add!

**Comment by ipm5130** [comment]
I had to delete my old repo bc of some issues and I completely forgot to ask to be added as a collaborator here, asking to be added one more time!

**Comment by sammoniot** [comment]
Please add me as a collaborator.
