### ISSUE TITLE
Mystery Text Discussion of cpi.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#54]
Post your screenshots and discuss your findings about cpi.txt here!

**Comment by MyeishaF** [comment]
In cpi.txt file someone is sailing from England to New York, on a ship called Olympia. It is possibly the prime minister. Parcels are being loaded abroad the ship, to be sold in New York. Poirot whoever they are seems to be the main character. Okay, so the prime minister was murdered after traveling to New York, on a ship called the Olympia. Sailing from England to New York City. There are two detectives Poirot and Japp trying to solve the case. There is definitely a murderer on the loose, the word death appears 27 times in the text. Each context is about a different person dying. Someone got shot in a car. The detectives were trying to protect the prime minister from assassination but failed. There are so many possibilities for this text. Someone is for sure on a killing spree and the detectives are on their trail. 
<img width="1440" alt="Screen Shot 2022-03-21 at 8 53 28 PM" src="https://user-images.githubusercontent.com/98820377/159387713-09324565-0bc1-4e82-a2cd-d536c984debe.png">
<img width="1440" alt="Screen Shot 2022-03-21 at 8 52 33 PM" src="https://user-images.githubusercontent.com/98820377/159387741-e40579ce-fa57-467e-b447-abffba59b6b3.png">
<img width="1226" alt="Screen Shot 2022-03-21 at 8 24 01 PM" src="https://user-images.githubusercontent.com/98820377/159387760-8b24505c-0b2b-4ad6-8e2e-29fcabbb5589.png">

**Comment by JiminyKricket0323** [comment]
It was very interesting to see that "mon ami i" is mentioned 11 times in the text and "elmer s dale" is mentioned 6 times in the text. First, I was wondering what is that even mean. But when I looked at on KWIC,  I realised that this system isn't reading the ' before "s". so it appears to be elmer s dale instead elmer's dale. And also "elmer s dale" is "mon ami_. I" in the text. (I have all of the screenshots but I'm not sure why I'm keep getting "Something went really wrong, and we can't process that file" every time I try to upload the screenshot files... HELP..?)

**Comment by JiminyKricket0323** [comment]
![SC TEXT 4](https://user-images.githubusercontent.com/98975456/159529366-77f24328-5c34-40fa-8f93-2c49ef8b18f9.png)
![SC TEXT 3](https://user-images.githubusercontent.com/98975456/159529372-6adcd4b9-7744-4db6-aa85-7aa61c2772ce.png)
![SC TEXT 2](https://user-images.githubusercontent.com/98975456/159529373-6ea8eef8-ab11-4806-be4f-1d63993bb288.png)
![SC TEXT 1](https://user-images.githubusercontent.com/98975456/159529376-daab8d17-7f33-4aa5-84e0-2fd53d6434b0.png)
