### ISSUE TITLE
Requests to Join this Repo as a Collaborator

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#56]
Please post here to introduce your GitHub self to our Newtfire GitHub organization and to this repo for Intro to Digital Humanities.

**Comment by tylerakam** [comment]
My username is @tylerakam. @ebeshero please add me as a collaborator!

**Comment by epp5198** [comment]
My username is @epp5198 please add me @ebeshero

**Comment by tyccott** [comment]
My username is @tyccott. @ebeshero please add me as a collaborator :)

**Comment by UAEFasool** [comment]
My username @UAEFasool. My name is Faisal. Add me

**Comment by JordanJ7** [comment]
My username is @JordanJ7

**Comment by Remdog712** [comment]
My username is @Remdog712 
please add me @ebeshero 
-Remington Orange

**Comment by mblankenberg25** [comment]
My username is @mblankenberg25 
please add me @ebeshero 
-Mason Blankenberg

**Comment by ZSchleger** [comment]
My username is @ZSchleger

**Comment by HadleighJae** [comment]
My username is @HadleighJae
Please add me @ebeshero 
~ Hadleigh Jae Bills

**Comment by ArtObssesed** [comment]
My Username Is @TealDragon21
Please Add Me @ebeshero 
-Riley Gank

**Comment by LPHerschell** [comment]
My username is @LPHerschell. Please add me @ebeshero.
- Lyndon Herschell

**Comment by justnobl** [comment]
My username is @justnobl please add me @mblankenberg25

**Comment by mckaylas615** [comment]
my username is @mckaylas615. please add me @ebeshero

**Comment by LizardWizard01** [comment]
My user is @LizardWizard01
Please add me @ebeshero

**Comment by SavannahRicks** [comment]
my username is @SavannahRicks so add me!

**Comment by Stach13** [comment]
My username is @Stach13, @ebeshero please add me as a collaborator to the introDH-Hub repo.

**Comment by ebeshero** [comment]
@JordanJ7 Hi Jordan!

**Comment by Seeedle** [comment]
Yo (●'◡'●)(●'◡'●)(●'◡'●) Add me as a collaborator, please! @Seeedle (～￣▽￣)～

**Comment by Reg157** [comment]
My username is @Reg157

**Comment by spookybeetle** [comment]
Hi I'm Milo, my user is @spookybeetle.

**Comment by ghost** [comment]
Hi my user is @spookybeetle, I need to be added as a collaborator.

**Comment by jmb9634** [comment]
My username is @jmb9634, could you add me as a collaborator? @ebeshero
