### ISSUE TITLE
Joining our DIGIT Newtfire GitHub Organization

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#71]
Please post here to introduce your GitHub self to our Newtfire GitHub organization and to this repo for Intro to Digital Humanities.

![This is an image](https://newtfire.org/courses/newt-mosaic4.png)

**Comment by mew-II** [comment]
Comment for the assignment, here's my account.
Note: this is Matthew Weitzel

**Comment by AshishNarisetty** [comment]
GitHub assignment comment.

**Comment by rcc5418** [comment]
Hello it is me Reece Cullen on GitHub, please add me to the github organizatoin

**Comment by lgmccurdy** [comment]
requesting add

**Comment by TylerDollard** [comment]
Tyler Dollard. Please add me

**Comment by J-Banko** [comment]
Commenting for the GitHub assignment

**Comment by rxp5417** [comment]
comment for assignment 
this is Ryan Patterson

**Comment by sjm7342** [comment]
Bonjour mes amis, je m'appelle Sean
Sean Martin!

**Comment by MadisonSciarrillo** [comment]
comment for assignment

**Comment by TommyMC2** [comment]
This is Tommy

**Comment by ebeshero** [comment]
I've invited everyone to this point!

**Comment by sammoniot** [comment]
This is Sam

**Comment by ebeshero** [comment]
I've invited everyone to this point!

**Comment by cbl5678** [comment]
My username is @cbl5678. @ebeshero please add me as a collaborator.

**Comment by ebeshero** [comment]
All here: if you did not yet accept my invitation to join this organization, please find it in your e-mail inbox, for the e-mail you used to create your GitHub account. As soon as you accept the invitation, you'll be a member of our DIGIT newtfire GitHub organization. :-)

**Comment by Cmk6316** [comment]
Github Assignment. This is Christian

**Comment by nhammer514** [comment]
This is Nathan. Please add me to the repo!

**Comment by ceq5032** [comment]
This is Chelsea Quijas. Please add me.

**Comment by ebeshero** [comment]
Okay! @ceq5032 and @Cmk6316 : I've sent you both invitations to join our GitHub organization. Please check the e-mail you used to create your GitHub account and accept my invitation. @nhammer514 : you're already a member!

**Comment by VocaloidOtaku39** [comment]
Hello again! I am @VocaloidOtaku39 , aka Alyssa Hopple. Will you include me in the DIGIT100 organization, please?

**Comment by gylertaydos** [comment]
Hey, Dr. B! I need added to this org (please and thank you).

**Comment by KaitlynScutella** [comment]
Commenting for the assignment, I need added! This is Kaitlyn Scutella.

**Comment by vnichols16** [comment]
May I be added to our repo please? It's Jordan :)

**Comment by Matthew-W8** [comment]
Hello, this is Matthew Wilpula. May I please be added it the repo?

**Comment by ebeshero** [comment]
@Matthew-W8 @vnichols16 @KaitlynScutella I've sent you invitations just now to join two things:

* to the newtfire GitHub organization (shared with my DIGIT classes and student projects)
* to the introDH-Hub repo
Please check the e-mail you used to set up your GitHub account and accept my invitations.
(Others in this thread are already in the repo and organization.)
