### ISSUE TITLE
Adding Hub Collaborators

### ISSUE THREAD

**Issue by Cullen-Mort** [newtfire/introDH-Hub#72]
My username is @Cullen-Mort . @ebeshero Please add me as a collaborator to this DH-Hub.

**Comment by sammoniot** [comment]
My name is @sammoniot. @ebeshero please add me as a collaborator to this DH-Hub.

**Comment by ebeshero** [comment]
Okay! @Cullen-Mort: I've sent you both invitations to join our GitHub organization. Please check the e-mail you used to create your GitHub account and accept my invitation. @sammoniot : you're already a member!
