### ISSUE TITLE
Mystery Text discussion of fc.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#77]
Post your screenshots and discuss your findings about fc.txt here!

**Comment by ebeshero** [comment]
I'm writing a response here to demonstrate! I found this interesting pattern in my view of ac.text.
![Screenshot 2023-03-14 at 13 01 00](https://user-images.githubusercontent.com/4014518/225081650-ec007d15-6f43-4ba0-9031-1bb924f14a49.png)

**Comment by J-Banko** [comment]
I chose to use fc.txt. At n-gram sizes above 4, there are no frequency counts above 5. At an n-gram of 4, frequencies range from 3 to 10. At n-gram 4, the second and third most common phrases are "I did not" and "I could not." The author seems to be speaking frequently of things that he was unable to do for whatever reason. Three times the author's "I could not" was followed by help being used a similar context to "I could not help but to wonder." 
![I could not](https://user-images.githubusercontent.com/124917045/225699016-460d25e9-ca6b-45d0-8de5-e8d637676b08.png)
![I did not](https://user-images.githubusercontent.com/124917045/225699052-436e46e9-9adb-4ced-bd61-ab38624d0de6.png)

**Comment by MadisonSciarrillo** [comment]
When doing the corpus analysis I chose fc.text. Multiple letters are talked about throughout the text. Letters being mainly sent to a woman named, Mrs. Saville, living in England. About a person that is about to set out on a long voyage. Looking at the word cloud I see a lot of darker terms where I questioned where they are related in the text, such as death, murder, and darkness. 
<img width="415" alt="Screenshot 2023-03-16 at 12 59 39 PM" src="https://user-images.githubusercontent.com/124644656/225780217-484662d9-8bbd-40e2-a3b9-f704a635cf56.png">
<img width="649" alt="Screenshot 2023-03-16 at 1 09 30 PM" src="https://user-images.githubusercontent.com/124644656/225780234-22d8f2bf-3459-48ac-8413-32f0138f654c.png">
<img width="618" alt="Screenshot 2023-03-16 at 1 09 47 PM" src="https://user-images.githubusercontent.com/124644656/225780253-109f947b-2f2e-48ef-89b5-5afe7fe5de5b.png">
<img width="735" alt="Screenshot 2023-03-16 at 1 06 46 PM" src="https://user-images.githubusercontent.com/124644656/225780397-b26de651-87bb-4527-b8cd-d27ee50f3a6d.png">

**Comment by Cmk6316** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/124918170/225786156-53eeca5d-8a1a-43f4-93e9-81bffd1c4925.png)
The corpus analysis of fc.text with the tool voyant revealed to me that the word 'man' was repeated 131 times. The use of the term is mainly used to describe a particular man named Beaufort in one instance so it seemed. In other instances it seems the narrator is describing other men he sees things happening to or encounters. I believe in other instances it is used as a figure of speech due to the time the letter was written. 
![Screenshot (32)](https://user-images.githubusercontent.com/124918170/225787532-e2e6b710-9740-4e29-b02d-9fb9b4548d3f.png)
N-gram size 4 gave me a frequency above 5. N-gram size 4 and 5 gave me double digit frequency counts. A repeated phrase that had a frequency count of 74 is "that is to say"

**Comment by bryanzack** [comment]
In fc.txt, a series of letters is present. Mostly being written to a Mrs. Saville in England by the recipients sister. The letters reference a voyage being undertaken, apparently a dangerous one. Below is a screenshot of the top n-grams of size 3 for this text. 
![VwZurDn7HK](https://user-images.githubusercontent.com/80417896/226128891-651137e4-4908-458c-8e49-8a0fdb122642.png) Out of the 5 n-grams, 4 are pretty standard english phrases, but 'the old man' is one that I found interesting; Who is the man being referenced over 29 times in the text?

Lastly, here is a visual representation of the n-gram pattern previously mentioned. 
![B9eZAVKUiW](https://user-images.githubusercontent.com/80417896/226129250-4649f6b2-586c-405d-8bf0-4b531efde418.png)

**Comment by lgmccurdy** [comment]
When putting fc.text into the Voyant Tool, the corpus analysis showed that the most frequent word was “man” which was repeated 131 times. After looking through the phrases, “the old man” was repeated several times in context to the word man. When put into AntConc, “the old man” had a frequency of 29. After looking through KWIC, the old man seems to be named “De Lacy” in which he resides in a cottage. Voyant Tool corpus analysis also showed “Elizabeth” being repeated 88 times, in which the phrase “Elizabeth my love” is used, revealing that the narrator must have a close relationship with her. 
<img width="390" alt="Screen Shot 2023-03-21 at 9 15 21 AM" src="https://user-images.githubusercontent.com/124915719/226624886-e9592b53-0ccf-4c10-82b6-03356fc19781.png">

<img width="1440" alt="Screen Shot 2023-03-21 at 9 32 03 AM" src="https://user-images.githubusercontent.com/124915719/226624935-a1574f3d-c906-48e5-a4e5-a1dceb16b5ca.png">

<img width="583" alt="Screen Shot 2023-03-21 at 9 44 11 AM" src="https://user-images.githubusercontent.com/124915719/226624953-5be519d6-b8d0-46e2-aa26-56d1e220dc4f.png">
