### ISSUE TITLE
Mystery Text discussion of ww.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#80]
Post your screenshots and discuss your findings about ww.txt here!

**Comment by rcc5418** [comment]
I decided to look at War of Worlds with our corpus analysis tools. Immediately noticeable in the word-frequency-graph is the large size of the word 'martian'. Coming in second for most used words, behind the obligatory 'said', it should come as no surprise that 'martian' is used so commonly considering the story.
![image](https://user-images.githubusercontent.com/113400168/225147282-217479c7-60e6-46d4-9871-d78aa40f94c3.png)
Taking a look at the text with Antconc, we can view multi-word phrases that are used commonly. Investigating 4 N-gram phrases, some fun sci-fi phrases are apparent. 'the edge of the', 'edge of the pit', and 'of the heat ray' bring to mind the terror of an alien invasion.
![image](https://user-images.githubusercontent.com/113400168/225147832-d3fb6529-25a0-4dab-bf16-99ef6c81c6ca.png)
The 4 N-gram phrases are also visible in this Wordcloud I made with an image of a War of Worlds toy I found online.
![image](https://user-images.githubusercontent.com/113400168/225150849-442beda1-b2d1-4e9f-9017-23fcb9aa75ce.png)

**Comment by Cullen-Mort** [comment]
The word Artilleryman was the one that made me realize this was "War of the Worlds" by Jules Verne and I'm not quite sure why.
![Screenshot 2023-03-16 125209](https://user-images.githubusercontent.com/123661751/225694420-99056993-6885-478a-a117-40762fb46a94.png)
This shows the top 25 most common words including Martian which makes the origin of it quite apparent. But not for me needed that artilleryman.
![Screenshot 2023-03-16 125756](https://user-images.githubusercontent.com/123661751/225695479-054da9da-ea84-413f-a0d0-aa05e673e5d0.png)
I turned the n-gram value to max (25) and when sentences are taken out with no punctuation stuff got a little funky. 
![Screenshot 2023-03-16 130335](https://user-images.githubusercontent.com/123661751/225696881-fdccb038-91d5-4e0f-9bd6-7a2393f4a4f8.png)
The highest n-gram that still has a frequency higher than 1.
