### ISSUE TITLE
Gone With The Wind Issue

### ISSUE THREAD

**Issue by sjm7342** [newtfire/introDH-Hub#81]
Within the portion of the radio play adaptation of _Gone With The _Wind,__ the name "Scarlett," the protagonist, is mentioned a total 57 times upon viewing in the KWIC perspective. Rhett, who is the on-off companion of Scarlett, is mentioned a total 64 times. When using AntConc and experimenting with the n-gram sizes, I discovered that not very many phrases exceeded past the 5th frequency. The larger the size the n-gram was, the lower the frequency was for phrases to be mentioned. The most interesting thing that I discovered was that with an n-gram size of 2, the term "I'm" could be seen with a minimum frequency of 19. No other term or phrase of any n-gram size had a minimum frequency that was that high.
<img width="1118" alt="AntConc 1" src="https://user-images.githubusercontent.com/124917523/225695620-3da5c8c1-d4ad-4ad9-90ec-1f51f1b1eeb3.png">
<img width="1134" alt="AntConc 3" src="https://user-images.githubusercontent.com/124917523/225695640-11f48917-041f-49b4-8893-87ec0f6b250e.png">
<img width="1140" alt="AntConc 6" src="https://user-images.githubusercontent.com/124917523/225695664-33a02967-25f7-42a1-b495-1d789be7028b.png">
<img width="1128" alt="AntConc 6 Again" src="https://user-images.githubusercontent.com/124917523/225695681-080b8f18-86d9-4e35-b871-73c75f06f8fd.png">

Within the word bubble, "Scarlett" and "Rhett" were the names mentioned much more than any other term throughout the script. The differing sizes of the word bubble definitely changed and many words were seen in some and exempt from others. However, the one thing that remained the same is that "Scarlett" and "Rhett" appeared extremely large throughout the word bubble in the middle, no matter how big the word bubble became. There were other terms, such as "you're," "I'm," and "oh" that were mentioned frequently, but still not nearly as much as "Scarlett" and "Rhett." There are many different terms that are used throughout the portion of the script, but very very few of them are repeated quite so much. With the exception of the two lead characters and some common phrases, the larger the word bubble became, the less varied the sizes of the letters became as well, besides the ones repeated time and again.
<img width="464" alt="gwtw word bubble 3" src="https://user-images.githubusercontent.com/124917523/225694866-3b1f0798-2366-4a52-a52b-2dcb085fee86.png">
<img width="419" alt="gwtw word bubble 4" src="https://user-images.githubusercontent.com/124917523/225694885-65a00113-71e8-4f8c-9e85-fa707bbf2f5f.png">

**Comment by VocaloidOtaku39** [comment]
This issue is interesting. It is really cool that the software can count how many times a specific word was written in the entire script!

**Comment by 03lizchavez** [comment]
Was this like a command+F thing to find this or was it more like just a program that has this feature/does this.

**Comment by ebeshero** [comment]
We'll be playing with this software in a few weeks after you complete the web development unit! I forgot I'd left the issue open from last semester! @03lizchavez @VocaloidOtaku39
