### ISSUE TITLE
Collaborator

### ISSUE THREAD

**Issue by MystKitteh** [newtfire/introDH-Hub#82]
My username is @MystKitteh. @ebeshero please add me as a collaborator to this DHClass-Hub

**Comment by morgs2005** [comment]
My username is @morgs2005 . @ebeshero please add me as a collaborator to this DHClass-Hub

**Comment by ebeshero** [comment]
@morgs2005 I've just sent you two invitations:

* to the newtfire GitHub organization (shared with my DIGIT classes and student projects)
* to the introDH-Hub repo
Please check the e-mail you used to set up your GitHub account and accept my invitations.
