### ISSUE TITLE
FA 23 Joining introDH-Hub and DIGIT Newtire GitHub Organization 

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#83]
Please post here to introduce your GitHub self to our Newtfire GitHub organization and to this repo for Intro to Digital Humanities.

![This is an image](https://newtfire.org/courses/newt-mosaic4.png)

**Comment by VocaloidOtaku39** [comment]
Hello, again, Professor B! I am @VocaloidOtaku39 ! Please add me to this DIGIT100 GitHub!

**Comment by SonicSpaceFan025** [comment]
Hi, I'm Kayla Hopple, also known as @SonicSpaceFan025 ! I'm ready to join the DIGIT100 GitHub!

**Comment by Rkd5429** [comment]
Hello, this is Ryan Dobson. I'm requesting to be added to the GitHub organization and the class repo.

**Comment by OH-ThatGuy** [comment]
Hey, this is Owen Helm. Commenting to join DIGIT100 GitHub.

**Comment by roram13** [comment]
Hi, this is Rachel Oram. Commenting to join DIGIT100 GitHub.

**Comment by agl5407** [comment]
it's @agl5407 requesting to be added to this DIGIT100 GitHub!

**Comment by macmiller8600** [comment]
Hi, this is Mackenzie Miller, commenting to join DIGIT100 GitHub.

**Comment by Fkhan2027** [comment]
Hi, this is Fatimah Khan, commenting to join DIGIT100 GitHub

**Comment by alissongossage** [comment]
Hi, this is Alisson Gossage commenting to join DIGIT100 Github.

**Comment by Rainbow7779** [comment]
Hi, this is Caleb Rainbow commenting to join DIGIT100 Github

**Comment by Cal16king** [comment]
Hey this is the other Caleb (King) commenting that I am present in the repo

**Comment by hsosia1** [comment]
Hello this is Hattie Sosia commenting to join DIGIT100 Github.

**Comment by ebeshero** [comment]
I've responded to everyone here so far and sent you two invitations:
1. to the newtfire GitHub organization (shared with my DIGIT classes and student projects)
2. to the introDH-Hub repo

Please check the e-mail you used to set up your GitHub account and accept my invitations.

**Comment by danikimmy** [comment]
This is Dani I need added

**Comment by jbh6352** [comment]
Hi this is Johnna Hibbetts, I'm commenting to be added to the Github
