### ISSUE TITLE
Mystery Text Discussion: mb.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#88]
Post your screenshots and discuss your findings about mb.txt here!

**Comment by GKon26** [comment]
While working with AntConc, I came across many references to whales and eventually the name Ishmael. After that, I knew exactly what text I was working with. I had a sneaking suspicion with all the whale talk. Whale is the first "non-filler" word at 22nd most popular word with 1228 results. Ironically, Moby Dick only appears 83 times, being the 102nd most popular 2gram. Granted, most of the ones before it aren't really much of anything. But "the whale" does show up 440 times so maybe they're not all "nothing" 2grams. 
![image](https://github.com/newtfire/introDH-Hub/assets/143760599/68507584-4bc1-48b4-966f-0f7d6765e385)
![image](https://github.com/newtfire/introDH-Hub/assets/143760599/778a747d-8410-44e0-9472-9659de5ff1e3)

**Comment by alissongossage** [comment]
N-gram sizes 1,2,3,4 and 5 give me frequencys above 5. N-gram sizes 1,2,3,4 and 5 gives me frequency counts in the double digits. “the sperm whale” gets repeated 116 times and “of the whale” gets repeated 110 times.
Phrases that occur 5-10 times are “out of site of land” and “the bottom of the sea. The higher the n-gram size, the lower the frequency. Basic words like “the” and “of” are the most frequent so they show up larger on voyant.

<img width="1436" alt="Screenshot 2023-11-01 at 12 18 36 AM" src="https://github.com/newtfire/introDH-Hub/assets/146370962/c150556c-7816-4d7c-af67-d5b9720c043b">
<img width="1226" alt="Screenshot 2023-11-01 at 12 13 00 AM" src="https://github.com/newtfire/introDH-Hub/assets/146370962/42ea3487-18fb-4371-9209-cd680780c568">
<img width="1241" alt="Screenshot 2023-11-01 at 12 12 49 AM" src="https://github.com/newtfire/introDH-Hub/assets/146370962/e9ab9521-c239-4125-9413-bd988400724b">
