### ISSUE TITLE
Embed Youtube Videos in GitPages

### ISSUE THREAD

**Issue by am0eba-byte** [newtfire/introDH-Hub#9]
``` 
<figure class="video_container">
  <iframe src="https://www.youtube.com/embed/W07E3NOc7pQ" frameborder="0" allowfullscreen="true"> </iframe>
</figure> 
```  

^^ I got the embed link by clicking "share" under the youtube video and clicking "embed," **You only have to copy the embed link from "src" to "true" (I think!)

**Comment by arrowarchive** [comment]
@am0eba-byte I'm going to be adding a video to my repository soon. Do you know if there's a way for me to embed the video file directly, or is it only through Youtube?

**Comment by am0eba-byte** [comment]
@arrowarchive I've never done it with videos before, but it should probably work just like any other image, i think? make sure you put the video file inside of your docs folder which holds your github website, and then when you create the link when writing the code in your HTML document just make sure that you link to the correct file name and relative file location. if it doesn't work, then i'm not sure and you might have to look it up
