### ISSUE TITLE
Mystery Text Discussion:  Radio Plays (your choice)

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#96]
Post your screenshots and discuss your findings about a radio play here! With this option be sure to identify which radio play(s) you scoped!

**Comment by lindseyxwood** [comment]
I chose to work with `thursday.txt` in the `radioPlays` folder. My findings are listed underneath the images.

![Screen Shot 2024-03-12 at 3 31 16 PM](https://github.com/newtfire/introDH-Hub/assets/143631193/ec969c5c-2de3-4477-9e44-4d2aee5567e4)
I worked with an N-gram size of 3 and my results are above. The most frequent occurrences were portions of the text that included who was speaking.

![Screen Shot 2024-03-12 at 3 31 58 PM](https://github.com/newtfire/introDH-Hub/assets/143631193/2fc651ee-bda2-48be-a990-f1567c774693)
I'm not surprised this text string is frequent considering the title of the text is "Who Was Thursday." I am curious as to why they named it that.

![Screen Shot 2024-03-12 at 3 32 46 PM](https://github.com/newtfire/introDH-Hub/assets/143631193/f58b4a4e-bea3-4cfb-bcfc-30d37a1a4743)
"The Mercury Theater" is the location of the radio station. References to this place are included throughout the text.
